site_name: BioPandas
site_url: http://rasbt.github.io/biopandas
site_author: Sebastian Raschka
site_description: Biopandas is a python package for working with molecular structures in pandas DataFrames.

repo_url: https://github.com/rasbt/biopandas/

#include_search: true
#theme: yeti

docs_dir: docs
site_favicon: favicon.ico

theme: bootstrap

markdown_extensions:
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - extra.css

copyright: Copyright &copy; 2015-2021 <a href="http://sebastianraschka.com">Sebastian Raschka</a>
google_analytics: ['UA-38457794-3', 'rasbt.github.io/biopandas']

nav:
    - Tutorials:
          - Working with PDB Structures in DataFrames: tutorials/Working_with_PDB_Structures_in_DataFrames.md
          - Working with MOL2 Structures in DataFrames: tutorials/Working_with_MOL2_Structures_in_DataFrames.md
    - API:
          - biopandas.pdb: api_subpackages/biopandas.pdb.md
          - biopandas.mol2: api_subpackages/biopandas.mol2.md
    - Changelog: CHANGELOG.md
    - Install: installation.md
    - Discuss: https://github.com/rasbt/biopandas/discussions
    - Contribute: CONTRIBUTING.md
    - Cite: citing.md
