site_name: BioPandas
site_url: http://rasbt.github.io/biopandas
site_author: Sebastian Raschka
site_description: Biopandas is a python package for working with molecular structures in pandas DataFrames.

repo_url: https://github.com/rasbt/biopandas

#include_search: true
docs_dir: sources
#theme: yeti

site_favicon: favicon.ico

theme_dir: cinder

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mathjax
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - extra.css

copyright: Copyright &copy; 2015-2018 <a href="http://sebastianraschka.com">Sebastian Raschka</a>
google_analytics: ['UA-38457794-3', 'rasbt.github.io/biopandas']

pages:
- Home: index.md
- Tutorials:
  - tutorials/Working_with_PDB_Structures_in_DataFrames.md
  - tutorials/Working_with_MOL2_Structures_in_DataFrames.md
- API:
  - api_subpackages/biopandas.pdb.md
  - api_subpackages/biopandas.mol2.md
- Changelog: changelog.md
- Installation: installation.md
- Contributing: contributing.md
- Citing: citing.md